Shopware.Service('privileges').addPrivilegeMappingEntry({
    category: 'permissions',
    parent: 'catalogues',
    key: 'merchandising',
    roles: {
        viewer: {
            privileges: [
                'strix_merch_rule:read',
                'strix_merch_pin:read',
                'strix_merch_filter_template:read',
                'strix_merch_sorting_template:read',
                'strix_merch_filter_template_category:read',
                'strix_merch_sorting_template_category:read',
                'strix_merch_audit_log:read',
                'strix_merch_click_aggregate:read',
                'strix_merch_customer_segment:read',
                'strix_merch_customer_segment_membership:read',
                'strix_merch_rule_category:read',
                'category:read',
                'product:read',
            ],
            dependencies: [],
        },
        editor: {
            privileges: [
                'strix_merch_rule:create',
                'strix_merch_rule:update',
                'strix_merch_pin:create',
                'strix_merch_pin:update',
                'strix_merch_filter_template:create',
                'strix_merch_filter_template:update',
                'strix_merch_sorting_template:create',
                'strix_merch_sorting_template:update',
                'strix_merch_rule_category:create',
                'strix_merch_rule_category:update',
                'strix_merch_rule_category:delete',
                'strix_merch_filter_template_category:create',
                'strix_merch_filter_template_category:update',
                'strix_merch_sorting_template_category:create',
                'strix_merch_sorting_template_category:update',
                'strix_merch_customer_segment:create',
                'strix_merch_customer_segment:update',
            ],
            dependencies: ['merchandising.viewer'],
        },
        creator: {
            privileges: [
                'strix_merch_rule:delete',
                'strix_merch_pin:delete',
                'strix_merch_filter_template:delete',
                'strix_merch_sorting_template:delete',
                'strix_merch_filter_template_category:delete',
                'strix_merch_sorting_template_category:delete',
                'strix_merch_customer_segment:delete',
                'strix_merch_customer_segment_membership:delete',
            ],
            dependencies: ['merchandising.editor'],
        },
    },
});
